### PR TITLE
ETS-2476 Reorders the bootstrap includes. Version 0.51.3

### PR DESCRIPTION
**Pull request by susannegernandt**

### CODE REVIEW

**Comment by filipe-esposito-fti** [comment]
It turns out the previous order of the imports was correct. We set our custom variables (the same ones that bootstrap uses on its CSS rules), and then we import bootstrap so that our custom values are used.

**Comment by filipe-esposito-fti** [comment]
And since now we updated the version of some packages, we just had to fix the units of some Bootstrap variables (from _px_ to _rem_).

**Comment by dknx01** [comment]
Please make sure, that these changes, at least if it is in the master, is also in the bitbucket repository.
If not we lost theses changes.

**Comment by filipe-esposito-fti** [comment]
> Please make sure, that these changes, at least if it is in the master, is also in the bitbucket repository.
> If not we lost theses changes.

Ok, on it right now.

**Comment by susannegernandt** [comment]
I would definitely approve Phil's changes here, but I can't, because I initially created the PR

**Review by dknx01 — APPROVED** [review]

**Pull request merged**
